### ISSUE TITLE
[Q] I've read your blog about fae. And I have some questions...

### ISSUE THREAD

**Issue by finscn** [englercj/fay#29]
1) Now,  Which project ( PIXI & fae) is your main goal ?
2) Which  project ( PIXI & fae) I should choose for my 2D html5 games ?
3) Why don't you take "Component Oriented Design" to PIXI ? 
4) this project has no updated since 2 months age , is it inactive or not to continue ?

Thanks

**Comment by pixelpicosean** [comment]
I'd suggest Pixi for you next game unless it's just kind of experimenting since Fae is still WIP.

**Comment by englercj** [comment]
1. Pixi, there is a long backstory to this repo, but the short version is I was experimenting with other ways of rendering. 
2. Pixi, this is not production ready and I don't plan to support it. 
3. I plan to, see my v5 project goals in the projects section of the pixi repo. 
4. This is deprecated in favor of pixi
